sweetyaar:
  log_path: sweetyaar.log
  log_level: DEBUG
  kill_switch_inactive_time_secs: 300
  default_starting_volume: 70

  nighttime_cutoff: '18:00'  # Use a MM:SS format.
  daytime_songs:
    - recordings/songs/daytime/*.wav
  nighttime_songs:
    - recordings/songs/nighttime/*.wav
  animals:
    yaar_callings: 
      - recordings/yaar_callings/*.wav
    animals_sounds:
      - recordings/animals/*.wav
  
  audio: 
    volume_step: 10

  interfaces:
    gpio:
      gpio_mode: BOARD
      animal_button_gpio_channel: 16
      songs_button_gpio_channel: 18
      button_debounce_ms: 1000

    keyboard:
      actions_mapping: 
        PLAY_RANDOM_ANIMAL_SOUND: a
        PLAY_RANDOM_SONG: s
        VOLUME_UP: + 
        VOLUME_DOWN: "-"
        STOP: t
        KILL_SWITCH: k
        REBOOT: r

    web:
      host: 0.0.0.0
      port: 80
      yaar_photos:
        - yaar-bg-1.jpeg
        - yaar-bg-2.jpeg
        - yaar-bg-3.jpeg
        - yaar-bg-4.jpeg
        - yaar-bg-5.jpeg
        - yaar-bg-6.jpeg
        - yaar-bg-7.jpeg
        - yaar-bg-8.png
        - yaar-bg-9.jpeg
        - yaar-bg-10.jpeg
        - yaar-bg-11.jpeg
        - yaar-bg-12.jpeg
        - yaar-bg-13.jpeg
        - yaar-bg-14.jpeg
        - yaar-bg-15.jpeg
      actions_mapping: 
        PLAY_RANDOM_ANIMAL_SOUND: random-animal-sound
        PLAY_RANDOM_SONG: random-song
        VOLUME_UP: volume-up
        VOLUME_DOWN: volume-down
        STOP: stop-playing
        KILL_SWITCH: kill-switch
        REBOOT: reboot
        OVERRIDE_DAYTIME: override-daytime
        OVERRIDE_NIGHTTIME: override-nighttime
